language: go
go:
- 1.x
addons:
  apt:
    packages:
    # Required for script that deploys to Chrome Web Store
    - python3-requests
    # Required to simulate display in end-to-end tests
    - xvfb
  # Required for end-to-end tests
  chrome: stable
before_install:
# gopherjs runs tests under Node.js. Install it.  We don't install from APT
# since that version is too old.
- . $HOME/.nvm/nvm.sh
- nvm install 'lts/*'
- nvm use 'lts/*'
# Install packages:
#   jsdom               Provides DOM implementation used in unit tests
#   source-map-support  Better stack traces in gopherjs tests
#   node-gyp            https://github.com/gopherjs/gopherjs/blob/master/doc/syscalls.md
#   selenium-webdriver  End-to-end tests in Chrome
#   chromedriver        Eor end-to-end tests in Chrome
#   mocha               Test framework for end-to-end tests
#   assert              For assertions in end-to-end tests
#   url-search-params   For validating URLSearchParams wrapper in unit tests
- npm install
- npm install jsdom source-map-support node-gyp selenium-webdriver chromedriver mocha assert
deploy:
  # Upload zip file to GitHub as a release
  - provider: releases
    api_key:
      secure: u+ZCN5GoEmN/JcG4rC5ioxoTGZ3wWHF4atS6scevqhv0EbHzfsnmxvX+mx0pGDPIVxfifeGafTkVckT3lbDYMeIAM+qyT4DJuF8R3gHpU9G+3rGCtfuBmKoCGjy+mpAPVLhxDXSvbZV4VSxhs45rS3UgBKo+icM6jSYiJht/8GLQrBLlq7592tSew6jEbaQLGi0UY/JoQX83Th4RzQa9RExTE54AVA6W6pHQP+hY8xi5zKn/PU1gSMqISUTeq1DDebnJX/qMqSZdPx9yT9ddI69SFtdTghDAscXWKIpu31NNZk/1b25sA5ZE5ytvrrlizcZAgCBxZJfMHlfxyl8lO68B5Zd0jH8meD1u561KrrtiuyDHrfBWt6qvUUmo1ztpZky5AoDozbPnS/8BBYELE8q5xyVoBgevYXGlGffRF4HsEsKKTbjuatbMO4Gkhy/apGlgxnZ+qlx2TFdEfOT97OMT12VSeZWqpvYisdFbsKHRdZOax8+UapE8jV7jlKgMZS5Io98jNsmxjHRrqDTgr7VEDfQMhOBIq+pnjj5UqR6BCFFagD5a7hBAZP+PmcbTWpRbTFeO/H8E9hAXy9JPybwRvcZ579s1dJ0DWUzeYHluccwu51tQ+H0lxq/QC7G88v7BLVUFf3HLJz7nlPEjtVT0wkmq33R2oDuE1opul2k=
    file: bin/chrome-ssh-agent.zip
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    # Deploy to Chrome Web Store
    script: make deploy-webstore
    skip_cleanup: true
    on:
      tags: true
